server:
  port: 9098

spring:
  datasource:
        url: jdbc:mysql://106.12.218.104:3306/graduate_ns?useUnicode=true&characterEncoding=UTF-8
        username: admin
        password: Shuairr1215.
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

  #jpa:
    #hibernate:
      #ddl-auto: update
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #show-sql: true

dataType: mysql